= Helloworld in C#

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository shows how to configure link:https://github.com/features/actions[GitHub Actions] and link:https://jreleaser.org/[JReleaser] to:

 * compile a helloworld app for the following targets:
   ** linux-musl-x86_64
   ** linux-x86_64
   ** linux-aarch_64
   ** windows-x86_64
   ** windows-aarch_64
   ** osx-x86_64
   ** osx-aarch_64
 * assemble zip distributions with JReleaser
 * create rolling early-access releases with JReleaser on every push to `main` branch

### Commands

## Build

Compile and assemble all Zip distributions by invoking

```sh
$ jreleaser assemble
```

You may perform a release by invoking

```sh
$ jreleaser release
```

NOTE: SLSA attestation can only be generated when running on GitHub Actions.

IMPORTANT: JReleaser requires 2 additional inputs that may be set as environment variables, `JRELEASER_PROJECT_VERSION` and `JRELEASER_GITHUB_TOKEN`.
More information about environment variable configuration may be found in the link:https://jreleaser.org/guide/latest/reference/environment.html[guide].
